-- BOGE S-4 Series Products
-- Disable RLS temporarily to allow inserts
ALTER TABLE products DISABLE ROW LEVEL SECURITY;

-- S 160-4 models (160 kW) - sorted by kW desc, then pressure desc
INSERT INTO products (brand, name, series, description, image_url, price, in_stock, specifications) VALUES
('Boge', 'BOGE S-4 Series — S 160–4 LF — 13 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 5.0 - 21.2 m³/min with a rated output of 160 kW, operating at 13 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 160–4 LF", "Max Pressure": "13 bar", "Effective Free Air Delivery": "5.0 - 21.2 m³/min", "Rated Output": "160 kW", "Fan Motor": "5.5 kW", "Dimensions (W × D × H)": "2980 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3750 kg", "Weight with super sound insulation": "3800 kg"}'),
('Boge', 'BOGE S-4 Series — S 160–4 — 13 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 21.2 m³/min with a rated output of 160 kW, operating at 13 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 160–4", "Max Pressure": "13 bar", "Effective Free Air Delivery": "21.2 m³/min", "Rated Output": "160 kW", "Fan Motor": "5.5 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3700 kg", "Weight with super sound insulation": "3750 kg"}'),
('Boge', 'BOGE S-4 Series — S 160–4 L — 13 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 19.3 m³/min with a rated output of 160 kW, operating at 13 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 160–4 L", "Max Pressure": "13 bar", "Effective Free Air Delivery": "19.3 m³/min", "Rated Output": "160 kW", "Fan Motor": "5.5 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3600 kg", "Weight with super sound insulation": "3650 kg"}'),
('Boge', 'BOGE S-4 Series — S 160–4 LF — 10 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 5.3 - 25.1 m³/min with a rated output of 160 kW, operating at 10 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 160–4 LF", "Max Pressure": "10 bar", "Effective Free Air Delivery": "5.3 - 25.1 m³/min", "Rated Output": "160 kW", "Fan Motor": "5.5 kW", "Dimensions (W × D × H)": "2980 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3750 kg", "Weight with super sound insulation": "3800 kg"}'),
('Boge', 'BOGE S-4 Series — S 160–4 — 10 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 25.0 m³/min with a rated output of 160 kW, operating at 10 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 160–4", "Max Pressure": "10 bar", "Effective Free Air Delivery": "25.0 m³/min", "Rated Output": "160 kW", "Fan Motor": "5.5 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3700 kg", "Weight with super sound insulation": "3750 kg"}'),
('Boge', 'BOGE S-4 Series — S 160–4 LF — 7.5 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 5.5 - 27.7 m³/min with a rated output of 160 kW, operating at 7.5 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 160–4 LF", "Max Pressure": "7.5 bar", "Effective Free Air Delivery": "5.5 - 27.7 m³/min", "Rated Output": "160 kW", "Fan Motor": "5.5 kW", "Dimensions (W × D × H)": "2980 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3750 kg", "Weight with super sound insulation": "3800 kg"}'),
('Boge', 'BOGE S-4 Series — S 160–4 — 7.5 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 28.1 m³/min with a rated output of 160 kW, operating at 7.5 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 160–4", "Max Pressure": "7.5 bar", "Effective Free Air Delivery": "28.1 m³/min", "Rated Output": "160 kW", "Fan Motor": "5.5 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3700 kg", "Weight with super sound insulation": "3750 kg"}');

-- S 132-4 models (132 kW)
INSERT INTO products (brand, name, series, description, image_url, price, in_stock, specifications) VALUES
('Boge', 'BOGE S-4 Series — S 132–4 LF — 13 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 5.0 - 17.9 m³/min with a rated output of 132 kW, operating at 13 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 132–4 LF", "Max Pressure": "13 bar", "Effective Free Air Delivery": "5.0 - 17.9 m³/min", "Rated Output": "132 kW", "Fan Motor": "3.0 kW", "Dimensions (W × D × H)": "2980 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3650 kg", "Weight with super sound insulation": "3700 kg"}'),
('Boge', 'BOGE S-4 Series — S 132–4 — 13 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 17.2 m³/min with a rated output of 132 kW, operating at 13 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 132–4", "Max Pressure": "13 bar", "Effective Free Air Delivery": "17.2 m³/min", "Rated Output": "132 kW", "Fan Motor": "3.0 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3650 kg", "Weight with super sound insulation": "3700 kg"}'),
('Boge', 'BOGE S-4 Series — S 132–4 LF — 10 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 5.3 - 21.8 m³/min with a rated output of 132 kW, operating at 10 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 132–4 LF", "Max Pressure": "10 bar", "Effective Free Air Delivery": "5.3 - 21.8 m³/min", "Rated Output": "132 kW", "Fan Motor": "3.0 kW", "Dimensions (W × D × H)": "2980 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3650 kg", "Weight with super sound insulation": "3700 kg"}'),
('Boge', 'BOGE S-4 Series — S 132–4 — 10 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 21.7 m³/min with a rated output of 132 kW, operating at 10 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 132–4", "Max Pressure": "10 bar", "Effective Free Air Delivery": "21.7 m³/min", "Rated Output": "132 kW", "Fan Motor": "3.0 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3650 kg", "Weight with super sound insulation": "3700 kg"}'),
('Boge', 'BOGE S-4 Series — S 132–4 L — 10 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 20.2 m³/min with a rated output of 132 kW, operating at 10 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 132–4 L", "Max Pressure": "10 bar", "Effective Free Air Delivery": "20.2 m³/min", "Rated Output": "132 kW", "Fan Motor": "3.0 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3550 kg", "Weight with super sound insulation": "3600 kg"}'),
('Boge', 'BOGE S-4 Series — S 132–4 LF — 7.5 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 5.5 - 25.0 m³/min with a rated output of 132 kW, operating at 7.5 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 132–4 LF", "Max Pressure": "7.5 bar", "Effective Free Air Delivery": "5.5 - 25.0 m³/min", "Rated Output": "132 kW", "Fan Motor": "3.0 kW", "Dimensions (W × D × H)": "2980 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3650 kg", "Weight with super sound insulation": "3700 kg"}'),
('Boge', 'BOGE S-4 Series — S 132–4 — 7.5 bar', 'S-4 Series', 'BOGE S-4 series rotary screw compressors are designed for industrial reliability and efficient compressed air delivery, optimized for continuous operation and stable performance. This configuration provides an effective free air delivery of 24.1 m³/min with a rated output of 132 kW, operating at 7.5 bar maximum pressure.', '/assets/boge-s20.jpg', 'Contact for pricing', true, '{"Type": "S 132–4", "Max Pressure": "7.5 bar", "Effective Free Air Delivery": "24.1 m³/min", "Rated Output": "132 kW", "Fan Motor": "3.0 kW", "Dimensions (W × D × H)": "2930 x 1620 x 1990 mm", "Compressed Air Outlet": "DN 80", "Weight with sound insulation": "3650 kg", "Weight with super sound insulation": "3700 kg"}');

-- Continue with remaining models... Due to character limit, I'll show you need to run the SQL in Supabase
-- Re-enable RLS
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
